version: "3.9"

services:
  flossly:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      NODE_ENV: production
    env_file:
      - .env.prod
    restart: unless-stopped
    volumes:
      - /var/www/flossly/public:/app/public
