export const crmAutomationDefaults = [
  {
    key: 'new_patient_enquiry_immediate',
    type: 'Email',
    name: 'New Enquiry - Welcome (Immediate)',
    subject: 'New Enquiry - Welcome',
    sending: 'Immediately when lead comes into CRM',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 0 },
    template: `<p>Hi [First Name],</p><p>Thank you for reaching out! We're thrilled you're considering us for your dental care. At [Practice Name], we believe every smile tells a story, and we can't wait to be part of yours.</p><p>Our team is carefully reviewing your enquiry and will contact you within 24 hours to discuss your needs and find the perfect appointment time that fits your schedule.</p><p>In the meantime, meet our award-winning team and explore our state-of-the-art facility [link to virtual tour].</p><p>Welcome to the family!</p>`,
  },
  {
    key: 'new_patient_enquiry_1_day',
    type: 'Email',
    name: 'New Enquiry - Why Us (Day 1)',
    subject: 'New Enquiry - Why Us',
    sending: '1 day afterward',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>Hi [First Name],</p><p>Choosing a dental practice is a big decision, and we want you to feel completely confident about joining our family.</p><p>Here's what our patients love most about us:</p><ul><li>Anxiety-free appointments with our gentle care approach</li><li>Same-day emergency availability</li><li>Advanced technology for pain-free treatments</li><li>A team that actually listens to your concerns</li></ul><p>Over 2,500 patients trust us with their smiles. Read their stories [link to testimonials] and discover why they've made us their dental home.</p><p>Ready to book? Simply reply to this email or call us at [phone number].</p>`,
  },
  {
    key: 'new_patient_enquiry_3_days',
    type: 'Email',
    name: 'New Enquiry - Final Nudge (Day 3)',
    subject: 'New Enquiry - Final Nudge',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Hi [First Name],</p><p>We noticed you haven't scheduled your appointment yet, and we wanted to reach out one more time.</p><p>Did you know? 94% of our new patients wish they'd booked sooner! Don't let dental anxiety or a busy schedule hold you back from the smile you deserve.</p><p>This month, we're offering extended evening hours to accommodate your lifestyle. Limited slots available!</p><p>Watch this 60-second video of patient transformations that will inspire you [link].</p><p>Your future smile is waiting - let's make it happen together.</p>`,
  },
  {
    key: 'send_price_list',
    type: 'Email',
    name: 'Send Price List',
    subject: 'Your requested price list',
    sending: 'Manual',
    enabled: false,
    template: `<p>Dear [Patient Name],</p><p>Thank you for contacting us. We appreciate your interest in our practice and are delighted that you're considering us for your dental care needs.</p><p>As requested, please find our practice price list attached to this email. We believe in transparent pricing and strive to make quality dental care accessible to all our patients.</p><p>If you have any questions about our services, pricing, or would like to schedule an appointment, please don't hesitate to reach out. Our friendly team is here to assist you and ensure you receive the best possible care.</p><p>We look forward to welcoming you to our practice and helping you achieve a healthy, beautiful smile.</p><p>Warm regards,<br>[Your Name]</p>`,
  },
  {
    key: 'practice_locations',
    type: 'Email',
    name: 'Send Practice Location',
    subject: 'Our location and directions',
    sending: 'Manual',
    enabled: false,
    template: `<p>Dear [Patient Name],</p><p>Thank you for your interest in visiting our dental clinic. We're conveniently located and easy to find.</p><p><strong>Our Address:</strong><br>[Street Address]<br>[City, State ZIP Code]</p><p><strong>Office Hours:</strong><br>[Days and Times]</p><p>Parking is available [on-site/nearby/street parking details], and our clinic is easily accessible by [public transportation details if applicable].</p><p>If you need directions or have any questions about finding us, please feel free to call us at [Phone Number]. We're happy to help guide you to our location.</p><p>We look forward to seeing you soon!</p><p>Best regards,<br>[Your Name]</p>`,
  },
  {
    key: 'lead_enquiry_day_1',
    type: 'Email',
    name: 'Welcome and Value (Immediate)',
    subject: 'Welcome to [Practice Name] - Your Smile Journey Starts Here',
    sending: 'Immediately when lead comes into CRM',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 0 },
    template: `<p>Hi [Patient Name],</p><p>Thank you for reaching out to [Practice Name]! We're thrilled you're considering us for your dental care.</p><p>I'm [Treatment Coordinator Name], and I'll be your personal guide throughout this journey. We understand that choosing the right dental practice is important, which is why we've helped over [X] patients achieve their dream smiles right here in [Location].</p><p>What makes us different? We combine cutting-edge technology with genuine care. Every patient receives a personalized treatment plan tailored to their unique needs and budget.</p><p>I'd love to schedule a complimentary consultation where we can discuss your goals and answer any questions. Simply reply to this email or call us at [Phone Number] - we have appointments available this week.</p><p>Looking forward to meeting you!</p><p>Warmly,<br>[Practice Name] Team<br>[Website] | [Phone Number]</p>`,
  },
  {
    key: 'lead_enquiry_day_3',
    type: 'Email',
    name: 'Educational Value (Day 3)',
    subject: "[Patient Name], here's what to expect at your first visit",
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Hi [Patient Name],</p><p>I wanted to share what happens during your first visit with us - no surprises, just exceptional care.</p><p>Your complimentary consultation includes:</p><ul><li>Comprehensive oral health assessment</li><li>3D imaging (if needed) so you can see exactly what we see</li><li>Personalized treatment options with transparent pricing</li><li>No-pressure discussion about your goals and concerns</li></ul><p>Many patients tell us they wish they'd come to see us sooner. The consultation typically takes 30-45 minutes, and you'll leave with a clear roadmap for your smile transformation.</p><p>Have questions before booking? I'm here to help. Just hit reply or call [Phone Number].</p><p>Best wishes,<br>[Practice Name] Team<br>[Address] | [Email]</p>`,
  },
  {
    key: 'lead_enquiry_day_5',
    type: 'Email',
    name: 'Social Proof (Day 7)',
    subject: 'See why patients choose [Practice Name]',
    sending: '7 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 7 },
    template: `<p>Hi [Patient Name],</p><p>Sometimes the best way to understand what we do is to hear from people just like you.</p><p>"I was nervous about dental treatment, but the team at [Practice Name] made me feel completely at ease. The results exceeded my expectations!" - Sarah M.</p><p>"Professional, caring, and transparent about costs. I finally found a dental practice I trust." - James T.</p><p>We're proud to maintain a 5-star rating because we treat every patient like family. Our approach is simple: listen first, recommend honest solutions, and deliver exceptional results.</p><p>Ready to experience the difference? Book your complimentary consultation today: [Phone Number]</p><p>We'd love to welcome you to our practice family.</p><p>Warmly,<br>[Practice Name] Team<br>[Website]</p>`,
  },
  {
    key: 'lead_enquiry_day_12',
    type: 'Email',
    name: 'Overcome Objections (Day 12)',
    subject: "Questions about dental treatment? We've got answers",
    sending: '12 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 12 },
    template: `<p>Hi [Patient Name],</p><p>I know choosing a dental practice can feel overwhelming. Here are the most common questions we hear:</p><p>"How much will it cost?" - We provide transparent pricing during your free consultation and offer flexible payment plans to fit any budget.</p><p>"Will it hurt?" - We use the latest pain-free techniques and sedation options. Your comfort is our priority.</p><p>"How long will it take?" - Most treatments are faster than you think. We'll create a timeline that works with your schedule.</p><p>"Are you accepting new patients?" - Yes. We'd love to welcome you to [Practice Name].</p><p>Still have questions? Let's chat. Call [Phone Number] or reply to this email.</p><p>Best wishes,<br>[Practice Name] Team<br>[Address] | [Email]</p>`,
  },
  {
    key: 'lead_enquiry_day_18',
    type: 'Email',
    name: 'Final Call to Action (Day 18)',
    subject: "[Patient Name], we'd love to help you achieve your smile goals",
    sending: '18 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 18 },
    template: `<p>Hi [Patient Name],</p><p>I wanted to reach out one last time because I genuinely believe we can help you achieve the smile you deserve.</p><p>At [Practice Name], we've transformed thousands of smiles, and we'd be honored to help you too. Whether you're looking for a routine check-up or a complete smile makeover, we're here to support you every step of the way.</p><p>Here's what happens next:</p><ul><li>Call us at [Phone Number] or reply to this email</li><li>Schedule your complimentary consultation at a time that works for you</li><li>Meet our friendly team and discover your personalized treatment options</li></ul><p>Our calendar fills quickly, so I encourage you to book soon. We have limited appointments available this month.</p><p>Looking forward to welcoming you.</p><p>Warmly,<br>[Practice Name] Team<br>[Website] | [Phone Number] | [Email]</p>`,
  },
  {
    key: 'composite_bonding_day_1',
    type: 'Email',
    name: 'Educational Introduction (Immediate)',
    subject: 'Transform your smile in just one appointment with composite bonding',
    sending: 'Immediately when lead comes into CRM',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 0 },
    template: `<p>Hi [Patient Name],</p><p>Dreaming of a flawless smile without the wait or high cost of veneers? Composite bonding might be exactly what you're looking for.</p><p>This revolutionary treatment can:</p><ul><li>Fix chips, cracks, and gaps in your teeth</li><li>Reshape uneven or worn teeth</li><li>Close gaps between teeth</li><li>Improve discoloration</li></ul><p>All in a single visit.</p><p>The best part? Composite bonding is painless, requires no drilling, and costs a fraction of traditional veneers. Most patients see dramatic results in just 60-90 minutes.</p><p>At [Practice Name], we specialize in natural-looking composite bonding that transforms smiles while preserving your natural teeth. Our expert team has completed over [X] successful bonding treatments.</p><p>Curious to see if composite bonding is right for you? Book your free consultation: [Phone Number]</p><p>We'll assess your smile and show you exactly what's possible.</p><p>Best wishes,<br>[Practice Name] Team<br>[Website] | [Address]</p>`,
  },
  {
    key: 'composite_bonding_day_3',
    type: 'Email',
    name: 'Before/After Social Proof (Day 4)',
    subject: 'See real composite bonding transformations from [Practice Name]',
    sending: '4 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 4 },
    template: `<p>Hi [Patient Name],</p><p>A picture is worth a thousand words - especially when it comes to composite bonding.</p><p>We've helped hundreds of patients achieve stunning smile transformations in just one visit. From fixing chipped front teeth to closing gaps and creating perfectly shaped smiles, the results speak for themselves.</p><p>What our patients say:</p><p>"I can't believe the difference! My teeth look completely natural and I'm smiling with confidence for the first time in years." - Emma L.</p><p>"Quick, painless, and affordable. Wish I'd done this years ago." - Michael R.</p><p>Composite bonding typically costs 60-70% less than porcelain veneers, with results that last 5-10 years with proper care.</p><p>Want to see your own transformation? Book your complimentary consultation today: [Phone Number]</p><p>We'll create a personalized treatment plan just for you, with transparent pricing and flexible payment options.</p><p>Looking forward to meeting you.</p><p>[Practice Name] Team<br>[Email] | [Website]</p>`,
  },
  {
    key: 'composite_bonding_day_5',
    type: 'Email',
    name: 'Process and Comfort (Day 8)',
    subject: 'What to expect during your composite bonding treatment',
    sending: '8 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 8 },
    template: `<p>Hi [Patient Name],</p><p>Let me walk you through exactly what happens during composite bonding - no mysteries, just facts.</p><p>Your Treatment Journey:</p><ul><li>Consultation (30 mins) - We discuss your goals, assess your teeth, and show you what's achievable</li><li>Preparation (15 mins) - We gently prepare your tooth surface (no drilling or pain)</li><li>Application (30-60 mins) - We apply and sculpt the composite resin to create your perfect smile</li><li>Finishing touches (15 mins) - Polish and perfect for a natural, beautiful result</li></ul><p>Total time: 60-90 minutes for most treatments</p><p>Anesthesia needed: Usually not required.</p><p>Recovery time: None - leave with your new smile immediately.</p><p>Many patients are amazed at how comfortable and quick the process is. You can even watch your smile transform in real-time.</p><p>Ready to get started? We're offering a 10% discount on composite bonding consultations booked this month.</p><p>Call [Phone Number] or reply to this email to claim your spot.</p><p>Warmly,<br>[Practice Name] Team<br>[Address] | [Phone Number]</p>`,
  },
  {
    key: 'composite_bonding_day_13',
    type: 'Email',
    name: 'Overcome Price Objections (Day 13)',
    subject: 'Affordable smile transformation - here is how we make it work',
    sending: '13 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 13 },
    template: `<p>Hi [Patient Name],</p><p>We believe everyone deserves a confident smile, which is why we've made composite bonding accessible to all our patients.</p><p>Investment: Composite bonding typically ranges from GBP [X] per tooth, significantly less than veneers at GBP [higher amount].</p><p>Flexible Payment Plans: Spread the cost over 6-12 months with 0% finance options (subject to approval).</p><p>What's included:</p><ul><li>Comprehensive consultation and assessment</li><li>Expert composite bonding treatment</li><li>Aftercare guidance and support</li><li>12-month satisfaction guarantee</li></ul><p>Think of it as an investment in yourself - your confidence, your career, your social life. Patients tell us their new smile changes everything.</p><p>Plus, this month we're offering up to 15% off composite bonding treatments when you book your consultation.</p><p>Don't let cost hold you back from the smile you deserve. Call [Phone Number] today to discuss your options.</p><p>Best wishes,<br>[Practice Name] Team<br>[Website] | [Email]</p>`,
  },
  {
    key: 'composite_bonding_day_18',
    type: 'Email',
    name: 'Urgency and Final CTA (Day 18)',
    subject: 'Last chance: 15% off composite bonding ends soon',
    sending: '18 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 18 },
    template: `<p>Hi [Patient Name],</p><p>This is your final reminder - our special offer on composite bonding treatments ends this week.</p><p>Save 15% when you book your consultation by [Date]. This exclusive discount won't last, and our calendar is filling fast.</p><p>Composite bonding can transform your smile in just one visit:</p><ul><li>No drilling or pain</li><li>Immediate results</li><li>Natural-looking finish</li><li>Lasts 5-10 years</li></ul><p>Hundreds of patients have trusted [Practice Name] with their smile transformations. Now it's your turn.</p><p>Act now: Call [Phone Number] or reply to this email to secure your discounted consultation.</p><p>Limited appointments available - don't miss out on this opportunity.</p><p>Looking forward to helping you achieve your dream smile.</p><p>Warmly,<br>[Practice Name] Team<br>[Website] | [Address] | [Phone Number]</p>`,
  },
  {
    key: 'invisalign_day_1',
    type: 'Email',
    name: 'Solution-Focused Introduction (Immediate)',
    subject: 'Straighten your smile discreetly with Invisalign',
    sending: 'Immediately when lead comes into CRM',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 0 },
    template: `<p>Hi [Patient Name],</p><p>Dreaming of straighter teeth but don't want the hassle of metal braces? You're not alone.</p><p>Invisalign clear aligners have revolutionized orthodontics, helping millions of adults achieve perfectly straight smiles without anyone noticing they're in treatment.</p><p>Why patients choose Invisalign:</p><ul><li>Virtually invisible - no one will know you're wearing them</li><li>Removable - eat, drink, and brush normally</li><li>Comfortable - no metal brackets or wires</li><li>Effective - treats crowding, gaps, overbites, and more</li><li>Fast results - most treatments complete in 6-18 months</li></ul><p>At [Practice Name], we're certified Invisalign providers with [X] successful cases completed. We use advanced 3D imaging to show you your new smile before you even start treatment.</p><p>Ready to discover if Invisalign is right for you? Book your free consultation and 3D smile simulation: [Phone Number]</p><p>We'll create a personalized treatment plan with transparent pricing - no hidden costs, no surprises.</p><p>Excited to help you achieve your dream smile.</p><p>Best wishes,<br>[Practice Name] Team<br>[Website] | [Address]</p>`,
  },
  {
    key: 'invisalign_day_3',
    type: 'Email',
    name: 'Visualization and Technology (Day 4)',
    subject: 'See your future smile before treatment begins',
    sending: '4 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 4 },
    template: `<p>Hi [Patient Name],</p><p>Imagine seeing exactly how your smile will look after Invisalign treatment - before you even commit.</p><p>At [Practice Name], we use cutting-edge 3D technology to create a digital preview of your smile transformation. You'll see every stage of your treatment journey, from day one to your final, perfect smile.</p><p>Your Invisalign journey:</p><ul><li>Free consultation - We assess your teeth and discuss your goals</li><li>3D smile preview - See your future smile in stunning detail</li><li>Custom aligners - Precision-crafted for your unique treatment</li><li>Regular check-ins - We monitor progress every 6-8 weeks</li><li>Beautiful results - Achieve the straight smile you've always wanted</li></ul><p>Real patient feedback:</p><p>"Seeing my smile preview made the decision easy. The treatment was exactly as shown - absolutely worth it." - Rachel K.</p><p>"I loved that I could remove my aligners for important meetings. No one at work even knew I was straightening my teeth." - David M.</p><p>Most Invisalign treatments take 12-18 months, but you'll start seeing results within weeks.</p><p>Book your complimentary consultation and 3D preview today: [Phone Number]</p><p>Looking forward to showing you what's possible.</p><p>Warmly,<br>[Practice Name] Team<br>[Email] | [Website]</p>`,
  },
  {
    key: 'invisalign_day_5',
    type: 'Email',
    name: 'Lifestyle Benefits (Day 8)',
    subject: 'Why busy professionals choose Invisalign',
    sending: '8 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 8 },
    template: `<p>Hi [Patient Name],</p><p>If you've been hesitating about teeth straightening because of your lifestyle, Invisalign might be the perfect solution.</p><p>Perfect for busy lives:</p><ul><li>Minimal appointments - Check-ins every 6-8 weeks (not monthly like braces)</li><li>No food restrictions - Remove aligners to eat whatever you want</li><li>No emergencies - No broken brackets or wires requiring urgent visits</li><li>Easy maintenance - Simply brush your aligners and teeth as normal</li><li>Professional appearance - Completely discreet during meetings and social events</li></ul><p>Many of our patients are working professionals, parents, and active individuals who need flexibility. Invisalign fits seamlessly into your life, not the other way around.</p><p>This month only: We're offering 15% off Invisalign treatment packages when you book your consultation.</p><p>That's a saving of up to GBP [X] on your smile transformation.</p><p>Ready to get started? Call [Phone Number] or reply to this email. Our calendar is filling quickly.</p><p>Best wishes,<br>[Practice Name] Team<br>[Address] | [Phone Number]</p>`,
  },
  {
    key: 'invisalign_day_13',
    type: 'Email',
    name: 'Financial Options (Day 13)',
    subject: 'Make Invisalign affordable with flexible payment plans',
    sending: '13 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 13 },
    template: `<p>Hi [Patient Name],</p><p>We know cost is an important consideration when investing in your smile. That's why we've made Invisalign accessible with flexible financing options.</p><p>Investment options:</p><ul><li>Full payment discount: Pay upfront and save GBP [X]</li><li>Interest-free plans: Spread payments over 12 months at 0% APR</li><li>Extended finance: Monthly plans up to 24 months available</li><li>Deposit: From just GBP [X] to start treatment</li></ul><p>Average Invisalign investment: GBP 2,500-4,500 (varies based on complexity)</p><p>What's included:</p><ul><li>All aligners and retainers</li><li>Regular monitoring appointments</li><li>3D smile preview and treatment planning</li><li>Aftercare and support</li></ul><p>Plus, this month we're offering up to 15% off - that's a potential saving of GBP [X].</p><p>Think of Invisalign as an investment in your confidence, career, and quality of life. Patients consistently tell us it's one of the best decisions they've ever made.</p><p>Let's create a payment plan that works for your budget. Call [Phone Number] today for your free consultation.</p><p>Warmly,<br>[Practice Name] Team<br>[Website] | [Email]</p>`,
  },
  {
    key: 'invisalign_day_18',
    type: 'Email',
    name: 'Social Proof and Urgency (Day 18)',
    subject: 'Join [X] patients who transformed their smiles with Invisalign',
    sending: '18 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 18 },
    template: `<p>Hi [Patient Name],</p><p>This is your final reminder about our special Invisalign offer - 15% off treatment packages ends [Date].</p><p>We've helped [X] patients achieve straighter, more confident smiles with Invisalign. Here's what they're saying:</p><p>"I wish I'd done this years ago. The process was so easy and the results are incredible." - Sophie T.</p><p>"Completely painless and no one noticed I was wearing them. Best investment ever." - Tom H.</p><p>"The team at [Practice Name] made everything simple. From consultation to final results, I felt supported every step." - Lisa M.</p><p>Don't let this opportunity pass. Invisalign can transform not just your smile, but your confidence and quality of life.</p><p>Final call to action:</p><ul><li>Call [Phone Number] by [Date] to claim your 15% discount</li><li>Limited consultation slots available</li><li>Join our family of happy, confident patients</li></ul><p>We'd be honored to be part of your smile transformation journey.</p><p>Looking forward to meeting you.</p><p>Best wishes,<br>[Practice Name] Team<br>[Website] | [Address] | [Phone Number]</p>`,
  },
  {
    key: 'check_up_day_1',
    type: 'Email',
    name: 'Health-Focused Introduction (Immediate)',
    subject: 'Your smile deserves expert care - book your dental exam today',
    sending: 'Immediately when lead comes into CRM',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 0 },
    template: `<p>Hi [Patient Name],</p><p>When was your last dental check-up? If you're like most people, it's probably been longer than you'd like to admit.</p><p>At [Practice Name], we believe preventative care is the foundation of lasting oral health. Our comprehensive dental exams do more than just check for cavities - we assess your overall oral health to catch small issues before they become big problems.</p><p>Your comprehensive exam includes:</p><ul><li>Thorough examination of teeth, gums, and soft tissues</li><li>Oral cancer screening</li><li>Gum disease assessment</li><li>Digital X-rays (if needed)</li><li>Personalized oral health advice</li><li>Professional cleaning (hygienist appointment)</li><li>Treatment plan for any issues identified</li></ul><p>Special offer: New patients receive a comprehensive exam, X-rays, and professional cleaning for just GBP [X] (usually GBP [Y]) - save GBP [Z].</p><p>Regular dental exams can save you thousands in future treatment costs by catching problems early. Plus, good oral health is linked to overall wellbeing, heart health, and longevity.</p><p>Ready to prioritize your oral health? Book your appointment today: [Phone Number]</p><p>We have early morning and evening slots available to fit your schedule.</p><p>Best wishes,<br>[Practice Name] Team<br>[Website] | [Address]</p>`,
  },
  {
    key: 'check_up_day_3',
    type: 'Email',
    name: 'Overcome Fear and Anxiety (Day 4)',
    subject: 'Nervous about the dentist? We understand, and we are here to help',
    sending: '4 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 4 },
    template: `<p>Hi [Patient Name],</p><p>Dental anxiety is incredibly common - you're definitely not alone. Many of our patients tell us they've avoided the dentist for years because of fear or past negative experiences.</p><p>Here's what makes [Practice Name] different:</p><p><strong>Our gentle approach:</strong></p><ul><li>We listen to your concerns without judgment</li><li>You're in control - we'll stop anytime you need a break</li><li>We explain everything before we do it (no surprises)</li><li>Modern pain-free techniques and sedation options available</li><li>Calm, spa-like environment designed for relaxation</li><li>Extra time allocated so you never feel rushed</li></ul><p>"I hadn't been to a dentist in 8 years because of anxiety. The team at [Practice Name] made me feel so comfortable. I actually didn't mind being there." - Jennifer S.</p><p>"They took the time to understand my fears and worked at my pace. Best dental experience I've ever had." - Mark P.</p><p>The longer you wait, the more complex (and expensive) treatment becomes. But we promise to make your visit as comfortable as possible.</p><p>New patient offer: Comprehensive exam and cleaning for just GBP [X] this month.</p><p>Take the first step - call [Phone Number] today. Let us show you that dental visits can actually be pleasant.</p><p>Warmly,<br>[Practice Name] Team<br>[Email] | [Website]</p>`,
  },
  {
    key: 'check_up_day_5',
    type: 'Email',
    name: 'Prevention Equals Savings (Day 8)',
    subject: 'Save thousands with regular dental exams',
    sending: '8 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 8 },
    template: `<p>Hi [Patient Name],</p><p>Here's a truth most dentists won't tell you upfront: Regular check-ups can save you thousands of pounds in future dental work.</p><p>The cost of prevention vs treatment:</p><ul><li>Regular exam and cleaning: GBP [X] every 6 months</li><li>Filling (caught early): GBP [X]</li><li>Root canal (problem ignored): GBP [X]-GBP [X]</li><li>Crown after root canal: GBP [X]</li><li>Extraction and implant (worst case): GBP [X]-GBP [X]</li></ul><p>See the difference? A simple exam that catches a small cavity can prevent thousands in complex treatment later.</p><p>Plus, gum disease and oral infections can lead to serious health issues including heart disease, diabetes complications, and stroke. Prevention isn't just about your teeth - it's about your overall health.</p><p>This month only: New patient comprehensive exam package for GBP [X] (save GBP [Y])</p><p>This includes:</p><ul><li>Full oral health assessment</li><li>Digital X-rays</li><li>Professional cleaning</li><li>Personalized treatment plan</li><li>Oral hygiene guidance</li></ul><p>Think of it as an investment in your health and future savings. Book your appointment today: [Phone Number]</p><p>Our friendly team is here to help you maintain optimal oral health for life.</p><p>Best wishes,<br>[Practice Name] Team<br>[Address] | [Phone Number]</p>`,
  },
  {
    key: 'check_up_day_13',
    type: 'Email',
    name: 'Convenience and Technology (Day 13)',
    subject: 'Modern dentistry that fits your busy schedule',
    sending: '13 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 13 },
    template: `<p>Hi [Patient Name],</p><p>We know you're busy. That's why we've designed our practice around your convenience.</p><p>Flexible scheduling:</p><ul><li>Early morning appointments (from 7:30 AM)</li><li>Evening appointments (until 7:00 PM)</li><li>Saturday availability</li><li>Same-day emergency slots</li><li>Online booking available 24/7</li></ul><p>Modern technology for faster visits:</p><ul><li>Digital X-rays (90% less radiation, instant results)</li><li>Advanced diagnostics that catch issues early</li><li>Efficient appointments that respect your time</li><li>Text/email reminders so you never forget</li><li>Digital treatment plans you can review at home</li></ul><p>Comfortable, modern environment:</p><ul><li>Spa-like atmosphere</li><li>Music or TV during treatment</li><li>Comfortable treatment chairs</li><li>Complimentary refreshments</li><li>Friendly, caring staff who remember your name</li></ul><p>We've streamlined everything to make dental care as easy and pleasant as possible. Most routine exams take just 45-60 minutes.</p><p>Special offer ends soon: New patient exam package for GBP [X] - save GBP [Y].</p><p>Book online at [Website] or call [Phone Number]. We have appointments available this week.</p><p>Looking forward to welcoming you.</p><p>Best wishes,<br>[Practice Name] Team<br>[Website] | [Email]</p>`,
  },
  {
    key: 'check_up_day_18',
    type: 'Email',
    name: 'Final Urgency (Day 18)',
    subject: 'Last chance: GBP [Y] off new patient dental exam ends [Date]',
    sending: '18 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 18 },
    template: `<p>Hi [Patient Name],</p><p>This is your final reminder - our new patient special offer ends [Date].</p><p>Final chance to save: Comprehensive exam, X-rays, and professional cleaning for just GBP [X] (regularly GBP [Y]).</p><p>Your oral health shouldn't wait. Here's why booking now matters:</p><ul><li>Catch problems early before they become painful and expensive</li><li>Professional cleaning removes buildup your toothbrush can't reach</li><li>Peace of mind knowing your oral health is in expert hands</li><li>Prevent future issues with personalized care advice</li><li>Save money with our limited-time new patient discount</li></ul><p>We've helped thousands of patients achieve and maintain healthy, beautiful smiles. Let us do the same for you.</p><p>Don't miss out:</p><ul><li>Call [Phone Number] by [Date] to claim this offer</li><li>Limited appointment slots available</li><li>Join our family of happy, healthy patients</li></ul><p>Our team is ready to welcome you with exceptional, gentle care.</p><p>Book now - your smile will thank you.</p><p>Warmly,<br>[Practice Name] Team<br>[Website] | [Address] | [Phone Number]</p>`,
  },
  {
    key: 'black_friday_enquiry_day_1',
    type: 'Email',
    name: 'Exclusive Black Friday Offer Just for You!',
    subject: 'Exclusive Black Friday Offer Just for You!',
    sending: '1 day after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>Hi [First Name], are you ready to take advantage of our Black Friday deal?</p><p>Save up to 30% on selected cosmetic treatments. Secure your spot with us today.</p>`,
  },
  {
    key: 'black_friday_enquiry_day_3',
    type: 'Email',
    name: 'Reminder: Black Friday Offers Ending Soon',
    subject: 'Reminder: Black Friday Offers Ending Soon',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Don't miss out on incredible savings!</p><p>Our Black Friday promotions end soon. Book your consultation now to see how we can elevate your smile.</p>`,
  },
  {
    key: 'black_friday_enquiry_day_5',
    type: 'Email',
    name: 'Last Chance! Black Friday Deals End Today',
    subject: 'Last Chance! Black Friday Deals End Today',
    sending: '5 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 5 },
    template: `<p>[First Name], today is the final day to claim your Black Friday discount.</p><p>Book to see us now and transform your smile at a fraction of the cost.</p>`,
  },
  {
    key: 'general_lead_nurture_day_1',
    type: 'Email',
    name: 'Thank You for Your Interest in [Practice Name]',
    subject: 'Thank You for Your Interest in [Practice Name]',
    sending: '1 day after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>We appreciate your enquiry and would love to help you on your dental journey!</p><p>We're here to help with all your dental needs and questions. Let us know what procedure you're interested in.</p>`,
  },
  {
    key: 'general_lead_nurture_day_3',
    type: 'Email',
    name: 'Meet Our Exceptional Expert Dental Team',
    subject: 'Meet Our Exceptional Expert Dental Team',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Get to know our highly skilled dental team dedicated to providing you with the best dental care.</p><p>Book your first appointment to experience why we're a cut above the rest.</p>`,
  },
  {
    key: 'general_lead_nurture_day_5',
    type: 'Email',
    name: 'Your Smile Journey Begins Here',
    subject: 'Your Smile Journey Begins Here',
    sending: '5 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 5 },
    template: `<p>Don't wait - join hundreds of happy patients who have trusted us with their smiles.</p><p>Let's schedule your first appointment today.</p>`,
  },
  {
    key: 'birthday_gift_day_1',
    type: 'Email',
    name: 'Happy Birthday from [Practice Name]!',
    subject: 'Happy Birthday from [Practice Name]!',
    sending: 'On birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 0 },
    template: `<p>Wishing you a wonderful birthday!</p><p>Enjoy a special gift from us - a 10% discount on your next treatment during your birthday month.</p>`,
  },
  {
    key: 'birthday_gift_day_3',
    type: 'Email',
    name: "Don't Forget Your Birthday Gift!",
    subject: "Don't Forget Your Birthday Gift!",
    sending: '2 days after birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 2 },
    template: `<p>We wanted to remind you of your birthday reward.</p><p>Book your appointment with us this month to enjoy our special offer.</p>`,
  },
  {
    key: 'birthday_gift_day_5',
    type: 'Email',
    name: 'Last Chance for Your Birthday Offer!',
    subject: 'Last Chance for Your Birthday Offer!',
    sending: '4 days after birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 4 },
    template: `<p>Your birthday month is ending soon - make sure to claim your 10% discount before it's gone!</p>`,
  },
  {
    key: 'black_friday_7_days_before',
    type: 'Email',
    name: 'Black Friday - Early Access (5 Days Before)',
    subject: 'VIP Early Access: Black Friday deals revealed',
    sending: '5 days before Black Friday',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: -5 },
    template: `<p>Hi [Patient Name],</p><p>Black Friday is coming, and we're giving you exclusive early access to our biggest sale of the year.</p><p>Your VIP Black Friday Preview:</p><ul><li>Up to 20% off all dental treatments</li><li>Special package deals on smile makeovers</li><li>0% finance on treatments over GBP [X]</li></ul><p>This is our most generous offer all year - and as a valued lead, you get first access before the general public.</p><p>Early bird booking opens: [Date/Time]</p><p>Sale ends: [Date] at midnight</p><p>Popular treatments like Invisalign, composite bonding, and teeth whitening typically sell out within 48 hours during our Black Friday sale. Last year, we were fully booked by Saturday morning.</p><p>Mark your calendar and get ready to save big on the smile you've been dreaming about.</p><p>Set your reminder: Call [Phone Number] on [Date] at [Time] to secure your slot before they're gone.</p><p>Looking forward to helping you achieve your best smile at our best prices.</p><p>Best wishes,<br>[Practice Name] Team<br>[Website] | [Address]</p>`,
  },
  {
    key: 'black_friday_launch',
    type: 'Email',
    name: 'Black Friday - Sale Launch (Morning)',
    subject: 'BLACK FRIDAY: 20% off starts now',
    sending: 'Black Friday morning',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: 0 },
    template: `<p>Hi [Patient Name],</p><p>It's here. Our Black Friday sale is officially live.</p><p>Today only - save up to 20% on:</p><ul><li>Invisalign clear aligners - save up to GBP [X]</li><li>Composite bonding - transform your smile for less</li><li>Teeth whitening - get camera-ready confidence</li><li>Dental implants - permanent solution, temporary price</li><li>Smile makeover packages - our biggest discount ever</li></ul><p>Plus exclusive bonuses:</p><ul><li>Free consultation (worth GBP [X])</li><li>Free teeth whitening with treatments over GBP [X]</li><li>0% finance available on all treatments</li><li>Priority booking for 2026 appointments</li></ul><p>Sale ends: Midnight tonight | Appointments remaining: Limited</p><p>Last year we filled our entire December and January calendar in just 24 hours. Don't miss this opportunity to invest in yourself at unbeatable prices.</p><p>Book now: Call [Phone Number] or visit [Website]</p><p>Appointments are filling fast.</p><p>Urgently yours,<br>[Practice Name] Team<br>[Phone Number] | [Email]</p>`,
  },
  {
    key: 'black_friday_midday',
    type: 'Email',
    name: 'Black Friday - Midday Urgency (Afternoon)',
    subject: 'Only 8 hours left: Black Friday slots filling fast',
    sending: 'Black Friday afternoon',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: 0, minHour: 12 },
    template: `<p>Hi [Patient Name],</p><p>Urgent: Our Black Friday sale ends at midnight, and we're nearly fully booked.</p><p>Slots remaining as of 2 PM:</p><ul><li>Invisalign consultations: 3 left</li><li>Composite bonding: 5 left</li><li>Teeth whitening: 7 left</li><li>Smile makeover packages: 2 left</li></ul><p>These are the lowest prices you'll see all year - up to 20% off plus free bonuses worth GBP [X].</p><p>Over [X] patients have already secured their discounted treatments today. Will you be one of them?</p><p>What you're missing if you don't act now:</p><ul><li>Up to GBP [X] in savings</li><li>Free teeth whitening (worth GBP [X])</li><li>Priority 2026 appointment slots</li><li>0% finance options</li></ul><p>Time remaining: 8 hours</p><p>Slots remaining: Single digits</p><p>Act now: Call [Phone Number] immediately or book online at [Website]</p><p>Urgently,<br>[Practice Name] Team<br>[Phone Number]</p>`,
  },
  {
    key: 'black_friday_last_chance',
    type: 'Email',
    name: 'Black Friday - Final Hours (Evening)',
    subject: 'Final call: Black Friday ends at midnight',
    sending: 'Black Friday evening',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: 0, minHour: 18 },
    template: `<p>Hi [Patient Name],</p><p>This is it. In less than 3 hours, our Black Friday sale will be gone forever.</p><p>Right now, we have just a handful of discounted treatment slots remaining:</p><ul><li>2 Invisalign packages</li><li>3 composite bonding appointments</li><li>4 teeth whitening sessions</li><li>1 smile makeover package</li></ul><p>Sale ends: Tonight at midnight</p><p>Final savings: Up to 20% off plus free bonuses</p><p>Slots left: Almost sold out</p><p>Do not wait: Call [Phone Number] right now or book at [Website]</p><p>After midnight, these prices are gone for an entire year.</p><p>Final urgency,<br>[Practice Name] Team<br>[Phone Number] | [Website]</p>`,
  },
  {
    key: 'black_friday_sale_ended',
    type: 'Email',
    name: 'Black Friday - Sale Ended (Saturday)',
    subject: 'You missed it - Black Friday sale is over',
    sending: 'Saturday morning after Black Friday',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: 1 },
    template: `<p>Hi [Patient Name],</p><p>Our Black Friday sale officially ended at midnight last night.</p><p>I'm reaching out because I noticed you didn't book your discounted treatment, and I wanted to make sure you didn't miss out due to a technical issue or oversight.</p><p>What happened yesterday:</p><ul><li>[X] patients booked discounted treatments</li><li>We filled our calendar through [Month]</li><li>Patients saved an average of GBP [X]</li><li>All promotional slots sold out by 11:47 PM</li></ul><p>Here's the good news: While the Black Friday sale is over, I can offer you a one-time 10% courtesy discount if you book your consultation this weekend.</p><p>Your exclusive weekend offer:</p><ul><li>10% off any treatment (not the full 20%, but better than regular pricing)</li><li>Valid only until Sunday at midnight</li><li>Must mention "Weekend Courtesy Offer" when booking</li></ul><p>This is genuinely your last opportunity for a discount until our next promotional period.</p><p>Book now: Call [Phone Number] and ask for the Weekend Courtesy Offer.</p><p>Don't let another year go by without the smile you deserve.</p><p>Last chance,<br>[Practice Name] Team<br>[Phone Number] | [Website]</p>`,
  },
  {
    key: 'birthday_day',
    type: 'Email',
    name: 'Birthday - Gift Email (Day 0)',
    subject: 'Birthday - Gift Email',
    sending: 'On birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 0 },
    template: `<p>Hi [First Name],</p><p>HAPPY BIRTHDAY!</p><p>Today is all about celebrating YOU, and we wanted to make your day even brighter with a special birthday gift from our team.</p><p>As our valued patient, we're giving you exclusive birthday access to treatments that will make you smile even wider this year:</p><ul><li>Complimentary smile enhancement consultation</li><li>Professional teeth whitening session</li><li>Priority booking privileges</li></ul><p>Your birthday gift is valid for 30 days - because your celebration shouldn't end today!</p><p>Book your birthday appointment here: [link]</p><p>Here's to another year of confident, radiant smiles. You deserve to shine!</p>`,
  },
  {
    key: 'birthday_reminder_20_days',
    type: 'Email',
    name: 'Birthday - Gift Reminder (Day 20)',
    subject: 'Birthday - Gift Reminder',
    sending: '20 days after birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 20 },
    template: `<p>Hi [First Name],</p><p>We hope you had an amazing birthday! Just a friendly reminder that your exclusive birthday gift is still waiting for you - but not for long.</p><p>You have just 10 days left to claim your complimentary treatments. Don't let this special opportunity slip away!</p><p>Hundreds of our patients tell us that using their birthday gift was the best decision they made all year.</p><p>Claim your gift now: [booking link]</p><p>Make this birthday month truly unforgettable!</p>`,
  },
]

export const crmAutomationGroups = [
  {
    key: 'manual_responses',
    title: 'Manual Responses',
    description: 'Quick-send templates for common CRM replies.',
    source: 'default',
    templateKeys: ['send_price_list', 'practice_locations'],
  },
  {
    key: 'new_patient_enquiry',
    title: 'New Patient Enquiry',
    description: 'Welcome and follow-up emails for new leads.',
    source: 'default',
    templateKeys: ['new_patient_enquiry_immediate', 'new_patient_enquiry_1_day', 'new_patient_enquiry_3_days'],
  },
  {
    key: 'black_friday',
    title: 'Black Friday Campaign',
    description: 'Seasonal offers and last-chance reminders.',
    source: 'default',
    templateKeys: ['black_friday_7_days_before', 'black_friday_launch', 'black_friday_midday', 'black_friday_last_chance', 'black_friday_sale_ended'],
  },
  {
    key: 'birthday',
    title: 'Birthday Outreach',
    description: 'Birthday greetings and reminders.',
    source: 'default',
    templateKeys: ['birthday_day', 'birthday_reminder_20_days'],
  },
  {
    key: 'lead_enquiry',
    title: 'New Lead Enquiry Automation',
    description: 'Immediate + day 3/7/12/18 lead enquiry follow-ups.',
    source: 'default',
    templateKeys: ['lead_enquiry_day_1', 'lead_enquiry_day_3', 'lead_enquiry_day_5', 'lead_enquiry_day_12', 'lead_enquiry_day_18'],
  },
  {
    key: 'composite_bonding',
    title: 'Lead Nurture - Composite Bonding',
    description: 'Lead nurture sequence for composite bonding.',
    source: 'default',
    templateKeys: ['composite_bonding_day_1', 'composite_bonding_day_3', 'composite_bonding_day_5', 'composite_bonding_day_13', 'composite_bonding_day_18'],
  },
  {
    key: 'invisalign',
    title: 'Lead Nurture - Invisalign',
    description: 'Lead nurture sequence for Invisalign.',
    source: 'default',
    templateKeys: ['invisalign_day_1', 'invisalign_day_3', 'invisalign_day_5', 'invisalign_day_13', 'invisalign_day_18'],
  },
  {
    key: 'check_up',
    title: 'Lead Nurture - Dental Exam',
    description: 'Lead nurture sequence for dental exams.',
    source: 'default',
    templateKeys: ['check_up_day_1', 'check_up_day_3', 'check_up_day_5', 'check_up_day_13', 'check_up_day_18'],
  },
  {
    key: 'black_friday_enquiry',
    title: 'Black Friday / Special Deal Enquiry',
    description: 'Black Friday lead nurture day 1/3/5 follow-ups.',
    source: 'default',
    templateKeys: ['black_friday_enquiry_day_1', 'black_friday_enquiry_day_3', 'black_friday_enquiry_day_5'],
  },
  {
    key: 'general_lead_nurture',
    title: 'General Lead Nurture',
    description: 'General day 1/3/5 lead nurture sequence.',
    source: 'default',
    templateKeys: ['general_lead_nurture_day_1', 'general_lead_nurture_day_3', 'general_lead_nurture_day_5'],
  },
  {
    key: 'birthday_gift',
    title: 'Birthday Gift',
    description: 'Birthday gift day 1/3/5 sequence.',
    source: 'default',
    templateKeys: ['birthday_gift_day_1', 'birthday_gift_day_3', 'birthday_gift_day_5'],
  },
]
