export const crmAutomationDefaults = [
  {
    key: 'new_patient_enquiry_immediate',
    type: 'Email',
    name: 'New Enquiry - Welcome (Immediate)',
    sending: 'Immediately when lead comes into CRM',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 0 },
    template: `<p>Hi [First Name],</p><p>Thank you for reaching out! We're thrilled you're considering us for your dental care. At [Practice Name], we believe every smile tells a story, and we can't wait to be part of yours.</p><p>Our team is carefully reviewing your enquiry and will contact you within 24 hours to discuss your needs and find the perfect appointment time that fits your schedule.</p><p>In the meantime, meet our award-winning team and explore our state-of-the-art facility [link to virtual tour].</p><p>Welcome to the family!</p>`,
  },
  {
    key: 'new_patient_enquiry_1_day',
    type: 'Email',
    name: 'New Enquiry - Why Us (Day 1)',
    sending: '1 day afterward',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>Hi [First Name],</p><p>Choosing a dental practice is a big decision, and we want you to feel completely confident about joining our family.</p><p>Here's what our patients love most about us:</p><ul><li>Anxiety-free appointments with our gentle care approach</li><li>Same-day emergency availability</li><li>Advanced technology for pain-free treatments</li><li>A team that actually listens to your concerns</li></ul><p>Over 2,500 patients trust us with their smiles. Read their stories [link to testimonials] and discover why they've made us their dental home.</p><p>Ready to book? Simply reply to this email or call us at [phone number].</p>`,
  },
  {
    key: 'new_patient_enquiry_3_days',
    type: 'Email',
    name: 'New Enquiry - Final Nudge (Day 3)',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Hi [First Name],</p><p>We noticed you haven't scheduled your appointment yet, and we wanted to reach out one more time.</p><p>Did you know? 94% of our new patients wish they'd booked sooner! Don't let dental anxiety or a busy schedule hold you back from the smile you deserve.</p><p>This month, we're offering extended evening hours to accommodate your lifestyle. Limited slots available!</p><p>Watch this 60-second video of patient transformations that will inspire you [link].</p><p>Your future smile is waiting - let's make it happen together.</p>`,
  },
  {
    key: 'black_friday_7_days_before',
    type: 'Email',
    name: 'Black Friday - Teaser (7 Days Before)',
    sending: '7 days before Black Friday',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: -7 },
    template: `<p>Hi [First Name],</p><p>We've been working on something extraordinary, and we can't keep it a secret any longer.</p><p>This Black Friday, we're launching our biggest promotion of the year - and it's going to transform the way you think about dental care.</p><p>Mark your calendar for November 29th. You won't want to miss this.</p><p>Set your reminder now, because when this drops, it's going to be incredible.</p><p>The countdown begins...</p>`,
  },
  {
    key: 'black_friday_launch',
    type: 'Email',
    name: 'Black Friday - Launch (Morning)',
    sending: 'Black Friday morning',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: 0 },
    template: `<p>Hi [First Name],</p><p>BLACK FRIDAY IS LIVE!</p><p>For the next 24 hours only, unlock exclusive access to premium dental treatments that will revolutionize your smile.</p><ul><li>Composite Bonding Transformation</li><li>Professional Teeth Whitening</li><li>Complete Smile Makeovers</li><li>Advanced Dental Examinations</li></ul><p>This is our ONE annual promotion where we make premium dental care more accessible than ever. Hundreds of appointments available, but they're filling FAST.</p><p>Secure your spot before midnight: [booking link]</p><p>Over 150 patients have already claimed their appointments in the first hour. Don't miss your chance!</p>`,
  },
  {
    key: 'black_friday_last_chance',
    type: 'Email',
    name: 'Black Friday - Last Chance (Evening)',
    sending: 'Black Friday evening (6 hours before deadline)',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: 0, minHour: 18 },
    template: `<p>Hi [First Name],</p><p>This is it - your last chance.</p><p>In just 6 hours, our Black Friday promotion disappears forever. We've already helped 300+ patients secure their dream smile today.</p><p>Only 25 appointment slots remaining.</p><p>Don't wake up tomorrow with regret. Your future self will thank you for taking action today.</p><p>Book now before midnight: [booking link]</p><p>Time is running out. Your smile transformation awaits.</p>`,
  },
  {
    key: 'birthday_day',
    type: 'Email',
    name: 'Birthday - Gift Email (Day 0)',
    sending: 'On birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 0 },
    template: `<p>Hi [First Name],</p><p>HAPPY BIRTHDAY!</p><p>Today is all about celebrating YOU, and we wanted to make your day even brighter with a special birthday gift from our team.</p><p>As our valued patient, we're giving you exclusive birthday access to treatments that will make you smile even wider this year:</p><ul><li>Complimentary smile enhancement consultation</li><li>Professional teeth whitening session</li><li>Priority booking privileges</li></ul><p>Your birthday gift is valid for 30 days - because your celebration shouldn't end today!</p><p>Book your birthday appointment here: [link]</p><p>Here's to another year of confident, radiant smiles. You deserve to shine!</p>`,
  },
  {
    key: 'birthday_reminder_20_days',
    type: 'Email',
    name: 'Birthday - Gift Reminder (Day 20)',
    sending: '20 days after birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 20 },
    template: `<p>Hi [First Name],</p><p>We hope you had an amazing birthday! Just a friendly reminder that your exclusive birthday gift is still waiting for you - but not for long.</p><p>You have just 10 days left to claim your complimentary treatments. Don't let this special opportunity slip away!</p><p>Hundreds of our patients tell us that using their birthday gift was the best decision they made all year.</p><p>Claim your gift now: [booking link]</p><p>Make this birthday month truly unforgettable!</p>`,
  },
]

export const crmAutomationGroups = [
  {
    key: 'new_patient_enquiry',
    title: 'New Patient Enquiry',
    description: 'Welcome and follow-up emails for new leads.',
    templateKeys: ['new_patient_enquiry_immediate', 'new_patient_enquiry_1_day', 'new_patient_enquiry_3_days'],
  },
  {
    key: 'black_friday',
    title: 'Black Friday Campaign',
    description: 'Seasonal offers and last-chance reminders.',
    templateKeys: ['black_friday_7_days_before', 'black_friday_launch', 'black_friday_last_chance'],
  },
  {
    key: 'birthday',
    title: 'Birthday Outreach',
    description: 'Birthday greetings and reminders.',
    templateKeys: ['birthday_day', 'birthday_reminder_20_days'],
  },
]
