export const crmAutomationDefaults = [
  {
    key: 'new_patient_enquiry_immediate',
    type: 'Email',
    name: 'New Enquiry - Welcome (Immediate)',
    sending: 'Immediately when lead comes into CRM',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 0 },
    template: `<p>Hi [First Name],</p><p>Thank you for reaching out! We're thrilled you're considering us for your dental care. At [Practice Name], we believe every smile tells a story, and we can't wait to be part of yours.</p><p>Our team is carefully reviewing your enquiry and will contact you within 24 hours to discuss your needs and find the perfect appointment time that fits your schedule.</p><p>In the meantime, meet our award-winning team and explore our state-of-the-art facility [link to virtual tour].</p><p>Welcome to the family!</p>`,
  },
  {
    key: 'new_patient_enquiry_1_day',
    type: 'Email',
    name: 'New Enquiry - Why Us (Day 1)',
    sending: '1 day afterward',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>Hi [First Name],</p><p>Choosing a dental practice is a big decision, and we want you to feel completely confident about joining our family.</p><p>Here's what our patients love most about us:</p><ul><li>Anxiety-free appointments with our gentle care approach</li><li>Same-day emergency availability</li><li>Advanced technology for pain-free treatments</li><li>A team that actually listens to your concerns</li></ul><p>Over 2,500 patients trust us with their smiles. Read their stories [link to testimonials] and discover why they've made us their dental home.</p><p>Ready to book? Simply reply to this email or call us at [phone number].</p>`,
  },
  {
    key: 'new_patient_enquiry_3_days',
    type: 'Email',
    name: 'New Enquiry - Final Nudge (Day 3)',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Hi [First Name],</p><p>We noticed you haven't scheduled your appointment yet, and we wanted to reach out one more time.</p><p>Did you know? 94% of our new patients wish they'd booked sooner! Don't let dental anxiety or a busy schedule hold you back from the smile you deserve.</p><p>This month, we're offering extended evening hours to accommodate your lifestyle. Limited slots available!</p><p>Watch this 60-second video of patient transformations that will inspire you [link].</p><p>Your future smile is waiting - let's make it happen together.</p>`,
  },
  {
    key: 'lead_enquiry_day_1',
    type: 'Email',
    name: 'Thanks for Reaching Out to [Practice Name]!',
    sending: '1 day after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>Hi [First Name], thank you for your enquiry!</p><p>We'd love to help you achieve your best smile. One of our team will reach out shortly to discuss your needs. In the meantime, here's a quick link to learn about our services.</p>`,
  },
  {
    key: 'lead_enquiry_day_3',
    type: 'Email',
    name: 'Are you ready to Transform Your smile?',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Hi [First Name], just checking in.</p><p>We'd love to schedule a consultation to answer any questions you might have about transforming your smile. Together, we can see what the best treatment options for you might be.</p>`,
  },
  {
    key: 'lead_enquiry_day_5',
    type: 'Email',
    name: "Don't Miss Out on Exceptional Dental Care",
    sending: '5 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 5 },
    template: `<p>[First Name], we value your interest!</p><p>Our dentists are booking fast - secure your spot today for a bespoke assessment and see for yourself why our patients smile so brightly.</p>`,
  },
  {
    key: 'composite_bonding_day_1',
    type: 'Email',
    name: 'Unlock your dream smile with us!',
    sending: '1 day after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>Hi [First Name], composite bonding can transform your smile instantly.</p><p>Here's a gallery of before and after photos - would you like to come visit us and discuss treatment options?</p>`,
  },
  {
    key: 'composite_bonding_day_3',
    type: 'Email',
    name: 'Composite Bonding FAQs Answered',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>We've answered patient questions about composite bonding - discover how durable and affordable it is with our payment plan options.</p><p>Does composite bonding hurt? Absolutely not, it's all on the surface of the tooth. You just have to lay back and relax while our clinicians work their magic! Let's book a consultation to discuss the process further and make a tailor-made plan for you.</p>`,
  },
  {
    key: 'composite_bonding_day_5',
    type: 'Email',
    name: 'Special Offer on Composite Bonding This Month',
    sending: '5 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 5 },
    template: `<p>Exclusive deal for new patients: Book composite bonding before [Date] and get a complimentary whitening session. Let's get you booked in before we run out!</p>`,
  },
  {
    key: 'invisalign_day_1',
    type: 'Email',
    name: "Your Dream smile in 12 months or less, yes, it's possible!",
    sending: '1 day after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>Hi [First Name], our aligner treatments offer discreet, effective teeth straightening.</p><p>Watch this short video to learn about the process before you schedule your 3D scan.</p>`,
  },
  {
    key: 'invisalign_day_3',
    type: 'Email',
    name: 'How Invisalign Can Fit Your Lifestyle',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Invisalign fits seamlessly into your busy life.</p><p>Let's talk about how other patients balance treatment, work, and a busy social life effortlessly.</p>`,
  },
  {
    key: 'invisalign_day_5',
    type: 'Email',
    name: 'Limited Slots Left On Our Aligner Promotion',
    sending: '5 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 5 },
    template: `<p>Interested in aligner treatment?</p><p>Book a consultation by [Date] to receive a GBP 200 discount off your treatment plan.</p>`,
  },
  {
    key: 'check_up_day_1',
    type: 'Email',
    name: 'Stay Healthy with a Comprehensive Dental Check-Up',
    sending: '1 day after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>Hi [First Name], regular dental check-ups are essential for a healthy smile.</p><p>Let's book your appointment today to keep you smiling brightly!</p>`,
  },
  {
    key: 'check_up_day_3',
    type: 'Email',
    name: 'What to Expect at Your Check-Up',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Worried about your first visit with us? Don't be!</p><p>Here's what happens during a dental examination to make you feel comfortable and well informed - and remember, you're in complete control.</p>`,
  },
  {
    key: 'check_up_day_5',
    type: 'Email',
    name: 'Book Your Check-Up Today & Receive a Free Dental Care Kit',
    sending: '5 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 5 },
    template: `<p>Book your check-up now and receive a complimentary oral care kit.</p><p>Take the first step to optimal dental health with us here at [Practice Name].</p>`,
  },
  {
    key: 'black_friday_enquiry_day_1',
    type: 'Email',
    name: 'Exclusive Black Friday Offer Just for You!',
    sending: '1 day after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>Hi [First Name], are you ready to take advantage of our Black Friday deal?</p><p>Save up to 30% on selected cosmetic treatments. Secure your spot with us today.</p>`,
  },
  {
    key: 'black_friday_enquiry_day_3',
    type: 'Email',
    name: 'Reminder: Black Friday Offers Ending Soon',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Don't miss out on incredible savings!</p><p>Our Black Friday promotions end soon. Book your consultation now to see how we can elevate your smile.</p>`,
  },
  {
    key: 'black_friday_enquiry_day_5',
    type: 'Email',
    name: 'Last Chance! Black Friday Deals End Today',
    sending: '5 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 5 },
    template: `<p>[First Name], today is the final day to claim your Black Friday discount.</p><p>Book to see us now and transform your smile at a fraction of the cost.</p>`,
  },
  {
    key: 'general_lead_nurture_day_1',
    type: 'Email',
    name: 'Thank You for Your Interest in [Practice Name]',
    sending: '1 day after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 1 },
    template: `<p>We appreciate your enquiry and would love to help you on your dental journey!</p><p>We're here to help with all your dental needs and questions. Let us know what procedure you're interested in.</p>`,
  },
  {
    key: 'general_lead_nurture_day_3',
    type: 'Email',
    name: 'Meet Our Exceptional Expert Dental Team',
    sending: '3 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 3 },
    template: `<p>Get to know our highly skilled dental team dedicated to providing you with the best dental care.</p><p>Book your first appointment to experience why we're a cut above the rest.</p>`,
  },
  {
    key: 'general_lead_nurture_day_5',
    type: 'Email',
    name: 'Your Smile Journey Begins Here',
    sending: '5 days after enquiry',
    enabled: false,
    trigger: { type: 'inquiry_days', days: 5 },
    template: `<p>Don't wait - join hundreds of happy patients who have trusted us with their smiles.</p><p>Let's schedule your first appointment today.</p>`,
  },
  {
    key: 'birthday_gift_day_1',
    type: 'Email',
    name: 'Happy Birthday from [Practice Name]!',
    sending: 'On birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 0 },
    template: `<p>Wishing you a wonderful birthday!</p><p>Enjoy a special gift from us - a 10% discount on your next treatment during your birthday month.</p>`,
  },
  {
    key: 'birthday_gift_day_3',
    type: 'Email',
    name: "Don't Forget Your Birthday Gift!",
    sending: '2 days after birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 2 },
    template: `<p>We wanted to remind you of your birthday reward.</p><p>Book your appointment with us this month to enjoy our special offer.</p>`,
  },
  {
    key: 'birthday_gift_day_5',
    type: 'Email',
    name: 'Last Chance for Your Birthday Offer!',
    sending: '4 days after birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 4 },
    template: `<p>Your birthday month is ending soon - make sure to claim your 10% discount before it's gone!</p>`,
  },
  {
    key: 'black_friday_7_days_before',
    type: 'Email',
    name: 'Black Friday - Teaser (7 Days Before)',
    sending: '7 days before Black Friday',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: -7 },
    template: `<p>Hi [First Name],</p><p>We've been working on something extraordinary, and we can't keep it a secret any longer.</p><p>This Black Friday, we're launching our biggest promotion of the year - and it's going to transform the way you think about dental care.</p><p>Mark your calendar for November 29th. You won't want to miss this.</p><p>Set your reminder now, because when this drops, it's going to be incredible.</p><p>The countdown begins...</p>`,
  },
  {
    key: 'black_friday_launch',
    type: 'Email',
    name: 'Black Friday - Launch (Morning)',
    sending: 'Black Friday morning',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: 0 },
    template: `<p>Hi [First Name],</p><p>BLACK FRIDAY IS LIVE!</p><p>For the next 24 hours only, unlock exclusive access to premium dental treatments that will revolutionize your smile.</p><ul><li>Composite Bonding Transformation</li><li>Professional Teeth Whitening</li><li>Complete Smile Makeovers</li><li>Advanced Dental Examinations</li></ul><p>This is our ONE annual promotion where we make premium dental care more accessible than ever. Hundreds of appointments available, but they're filling FAST.</p><p>Secure your spot before midnight: [booking link]</p><p>Over 150 patients have already claimed their appointments in the first hour. Don't miss your chance!</p>`,
  },
  {
    key: 'black_friday_last_chance',
    type: 'Email',
    name: 'Black Friday - Last Chance (Evening)',
    sending: 'Black Friday evening (6 hours before deadline)',
    enabled: false,
    trigger: { type: 'black_friday', offsetDays: 0, minHour: 18 },
    template: `<p>Hi [First Name],</p><p>This is it - your last chance.</p><p>In just 6 hours, our Black Friday promotion disappears forever. We've already helped 300+ patients secure their dream smile today.</p><p>Only 25 appointment slots remaining.</p><p>Don't wake up tomorrow with regret. Your future self will thank you for taking action today.</p><p>Book now before midnight: [booking link]</p><p>Time is running out. Your smile transformation awaits.</p>`,
  },
  {
    key: 'birthday_day',
    type: 'Email',
    name: 'Birthday - Gift Email (Day 0)',
    sending: 'On birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 0 },
    template: `<p>Hi [First Name],</p><p>HAPPY BIRTHDAY!</p><p>Today is all about celebrating YOU, and we wanted to make your day even brighter with a special birthday gift from our team.</p><p>As our valued patient, we're giving you exclusive birthday access to treatments that will make you smile even wider this year:</p><ul><li>Complimentary smile enhancement consultation</li><li>Professional teeth whitening session</li><li>Priority booking privileges</li></ul><p>Your birthday gift is valid for 30 days - because your celebration shouldn't end today!</p><p>Book your birthday appointment here: [link]</p><p>Here's to another year of confident, radiant smiles. You deserve to shine!</p>`,
  },
  {
    key: 'birthday_reminder_20_days',
    type: 'Email',
    name: 'Birthday - Gift Reminder (Day 20)',
    sending: '20 days after birthday',
    enabled: false,
    trigger: { type: 'birthday_offset', days: 20 },
    template: `<p>Hi [First Name],</p><p>We hope you had an amazing birthday! Just a friendly reminder that your exclusive birthday gift is still waiting for you - but not for long.</p><p>You have just 10 days left to claim your complimentary treatments. Don't let this special opportunity slip away!</p><p>Hundreds of our patients tell us that using their birthday gift was the best decision they made all year.</p><p>Claim your gift now: [booking link]</p><p>Make this birthday month truly unforgettable!</p>`,
  },
]

export const crmAutomationGroups = [
  {
    key: 'new_patient_enquiry',
    title: 'New Patient Enquiry',
    description: 'Welcome and follow-up emails for new leads.',
    templateKeys: ['new_patient_enquiry_immediate', 'new_patient_enquiry_1_day', 'new_patient_enquiry_3_days'],
  },
  {
    key: 'black_friday',
    title: 'Black Friday Campaign',
    description: 'Seasonal offers and last-chance reminders.',
    templateKeys: ['black_friday_7_days_before', 'black_friday_launch', 'black_friday_last_chance'],
  },
  {
    key: 'birthday',
    title: 'Birthday Outreach',
    description: 'Birthday greetings and reminders.',
    templateKeys: ['birthday_day', 'birthday_reminder_20_days'],
  },
  {
    key: 'lead_enquiry',
    title: 'New Lead Enquiry Automation',
    description: 'Day 1/3/5 lead enquiry follow-up sequence.',
    templateKeys: ['lead_enquiry_day_1', 'lead_enquiry_day_3', 'lead_enquiry_day_5'],
  },
  {
    key: 'composite_bonding',
    title: 'Lead Nurture - Composite Bonding',
    description: 'Lead nurture sequence for composite bonding.',
    templateKeys: ['composite_bonding_day_1', 'composite_bonding_day_3', 'composite_bonding_day_5'],
  },
  {
    key: 'invisalign',
    title: 'Lead Nurture - Invisalign',
    description: 'Lead nurture sequence for Invisalign.',
    templateKeys: ['invisalign_day_1', 'invisalign_day_3', 'invisalign_day_5'],
  },
  {
    key: 'check_up',
    title: 'Lead Nurture - Check-Up',
    description: 'Lead nurture sequence for check-ups.',
    templateKeys: ['check_up_day_1', 'check_up_day_3', 'check_up_day_5'],
  },
  {
    key: 'black_friday_enquiry',
    title: 'Black Friday / Special Deal Enquiry',
    description: 'Black Friday lead nurture day 1/3/5 follow-ups.',
    templateKeys: ['black_friday_enquiry_day_1', 'black_friday_enquiry_day_3', 'black_friday_enquiry_day_5'],
  },
  {
    key: 'general_lead_nurture',
    title: 'General Lead Nurture',
    description: 'General day 1/3/5 lead nurture sequence.',
    templateKeys: ['general_lead_nurture_day_1', 'general_lead_nurture_day_3', 'general_lead_nurture_day_5'],
  },
  {
    key: 'birthday_gift',
    title: 'Birthday Gift',
    description: 'Birthday gift day 1/3/5 sequence.',
    templateKeys: ['birthday_gift_day_1', 'birthday_gift_day_3', 'birthday_gift_day_5'],
  },
]
