ALTER TABLE "DiaryTreatmentPlanItems"
  ADD COLUMN IF NOT EXISTS "paymentPlan"  VARCHAR(30)  DEFAULT 'private',
  ADD COLUMN IF NOT EXISTS "referrerId"   INTEGER,
  ADD COLUMN IF NOT EXISTS "referrerName" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "invoiceDesc"  VARCHAR(300),
  ADD COLUMN IF NOT EXISTS "showOnInvoice" BOOLEAN DEFAULT TRUE;
