UPDATE "CrmAutomationTemplates"
SET "subject" = CASE "key"
  WHEN 'new_patient_enquiry_immediate' THEN 'New Enquiry - Welcome'
  WHEN 'new_patient_enquiry_1_day' THEN 'New Enquiry - Why Us'
  WHEN 'new_patient_enquiry_3_days' THEN 'New Enquiry - Final Nudge'
  WHEN 'lead_enquiry_day_1' THEN 'Thanks for Reaching Out to [Practice Name]!'
  WHEN 'lead_enquiry_day_3' THEN 'Are you ready to Transform Your smile?'
  WHEN 'lead_enquiry_day_5' THEN 'Don''t Miss Out on Exceptional Dental Care'
  WHEN 'composite_bonding_day_1' THEN 'Unlock your dream smile with us!'
  WHEN 'composite_bonding_day_3' THEN 'Composite Bonding FAQs Answered'
  WHEN 'composite_bonding_day_5' THEN 'Special Offer on Composite Bonding This Month'
  WHEN 'invisalign_day_1' THEN 'Your Dream smile in 12 months or less, yes, it''s possible!'
  WHEN 'invisalign_day_3' THEN 'How Invisalign Can Fit Your Lifestyle'
  WHEN 'invisalign_day_5' THEN 'Limited Slots Left On Our Aligner Promotion'
  WHEN 'check_up_day_1' THEN 'Stay Healthy with a Comprehensive Dental Check-Up'
  WHEN 'check_up_day_3' THEN 'What to Expect at Your Check-Up'
  WHEN 'check_up_day_5' THEN 'Book Your Check-Up Today & Receive a Free Dental Care Kit'
  WHEN 'black_friday_enquiry_day_1' THEN 'Exclusive Black Friday Offer Just for You!'
  WHEN 'black_friday_enquiry_day_3' THEN 'Reminder: Black Friday Offers Ending Soon'
  WHEN 'black_friday_enquiry_day_5' THEN 'Last Chance! Black Friday Deals End Today'
  WHEN 'general_lead_nurture_day_1' THEN 'Thank You for Your Interest in [Practice Name]'
  WHEN 'general_lead_nurture_day_3' THEN 'Meet Our Exceptional Expert Dental Team'
  WHEN 'general_lead_nurture_day_5' THEN 'Your Smile Journey Begins Here'
  WHEN 'birthday_gift_day_1' THEN 'Happy Birthday from [Practice Name]!'
  WHEN 'birthday_gift_day_3' THEN 'Don''t Forget Your Birthday Gift!'
  WHEN 'birthday_gift_day_5' THEN 'Last Chance for Your Birthday Offer!'
  WHEN 'black_friday_7_days_before' THEN 'Black Friday - Teaser'
  WHEN 'black_friday_launch' THEN 'Black Friday - Launch'
  WHEN 'black_friday_last_chance' THEN 'Black Friday - Last Chance'
  WHEN 'birthday_day' THEN 'Birthday - Gift Email'
  WHEN 'birthday_reminder_20_days' THEN 'Birthday - Gift Reminder'
  ELSE "name"
END
WHERE "subject" IS NULL OR "subject" = '';
