import { DataTypes } from 'sequelize'
import sequelize from '../../utils/db'

export const DiaryPatient = sequelize.define(
  'DiaryPatients',
  {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    organisationId: { type: DataTypes.INTEGER, allowNull: false },
    title: { type: DataTypes.STRING(20), allowNull: true },
    sex: { type: DataTypes.STRING(20), allowNull: true },
    firstName: { type: DataTypes.STRING(80), allowNull: false },
    middleName: { type: DataTypes.STRING(80), allowNull: true },
    lastName: { type: DataTypes.STRING(80), allowNull: false },
    preferredName: { type: DataTypes.STRING(80), allowNull: true },
    niNumber: { type: DataTypes.STRING(40), allowNull: true },
    nhsNumber: { type: DataTypes.STRING(40), allowNull: true },
    insuranceNumber: { type: DataTypes.STRING(80), allowNull: true },
    legacyId: { type: DataTypes.STRING(80), allowNull: true },
    imagingId: { type: DataTypes.STRING(80), allowNull: true },
    ethnicity: { type: DataTypes.STRING(80), allowNull: true },
    address1: { type: DataTypes.STRING(200), allowNull: true },
    address2: { type: DataTypes.STRING(200), allowNull: true },
    address3: { type: DataTypes.STRING(200), allowNull: true },
    town: { type: DataTypes.STRING(120), allowNull: true },
    county: { type: DataTypes.STRING(120), allowNull: true },
    postcode: { type: DataTypes.STRING(20), allowNull: true },
    homePhone: { type: DataTypes.STRING(40), allowNull: true },
    workPhone: { type: DataTypes.STRING(40), allowNull: true },
    dob: { type: DataTypes.DATEONLY, allowNull: true },
    mobile: { type: DataTypes.STRING(40), allowNull: true },
    preferredPhone: { type: DataTypes.STRING(40), allowNull: true },
    email: { type: DataTypes.STRING(120), allowNull: true },
    doctor: { type: DataTypes.STRING(120), allowNull: true },
    occupation: { type: DataTypes.STRING(120), allowNull: true },
    family: { type: DataTypes.STRING(200), allowNull: true },
    marketingConsent: { type: DataTypes.STRING(10), allowNull: true },
    receiveSms: { type: DataTypes.BOOLEAN, allowNull: true },
    receiveEmail: { type: DataTypes.BOOLEAN, allowNull: true },
    paymentPlan: { type: DataTypes.STRING(40), allowNull: true },
    dentist: { type: DataTypes.STRING(120), allowNull: true },
    hygienist: { type: DataTypes.STRING(120), allowNull: true },
    dentistRecallInterval: { type: DataTypes.STRING(40), allowNull: true },
    nextDentistRecall: { type: DataTypes.DATEONLY, allowNull: true },
    hygienistRecallInterval: { type: DataTypes.STRING(40), allowNull: true },
    nextHygienistRecall: { type: DataTypes.DATEONLY, allowNull: true },
    acquisitionSource: { type: DataTypes.STRING(120), allowNull: true },
    defaultDentistId: { type: DataTypes.INTEGER, allowNull: true },
    recallMethod: { type: DataTypes.STRING(20), allowNull: true },
    recallInterval: { type: DataTypes.STRING(20), allowNull: true },
    rawData: { type: DataTypes.JSONB, allowNull: true },
  },
  { tableName: 'DiaryPatients', timestamps: true }
)
